local L = AceLibrary("AceLocale-2.2"):new("ExperienceFu")

L:RegisterTranslations("frFR", function() return {
    ["Current XP"] = "Expérience actuelle",
    ["Gained"] = "Gain",
    ["Level"] = "Niveau",
    ["Pet XP"] = "Expérience du familier",
    ["Pet level"] = "Niveau du familier",
    ["Remaining"] = "Restant",
    ["Reset session"] = "Redémarrer la session",
    ["Rest XP"] = "Expérience de repos",
    ["Show XP/hour"] = "Afficher PX/heure",
    ["Show current XP"] = "Afficher l'expérience actuelle",
    ["Show percent"] = "Afficher en pourcentage",
    ["Show pet XP"] = "Afficher l'expérience du familier",
    ["Show rest XP"] = "Afficher l'expérience de repos",
    ["Show time to level"] = "Afficher le temps restant avant niveau",
    ["Show value"] = "Afficher la valeur",
    ["Time this level"] = "Durée de ce niveau",
    ["Time this session"] = "Durée de cette session",
    ["Time to level for this level"] = "Temps avant niveau pour ce niveau",
    ["Time to level for this session"] = "Temps avant niveau pour cette session",
    ["Total XP this level"] = "Expérience totale de ce niveau",
    ["Total XP this session"] = "Expérience totale de cette session",
    ["Total time played"] = "Temps de jeu total",
    ["View as Remaining XP"] = "Voir l'expérience restante",
    ["XP/hour this level"] = "PX/heure pour ce niveau",
    ["XP/hour this session"] = "PX/heure pour cette session",
    ["Statistics"] = "Statistiques",
    ["Show in relation to level"] = "Afficher par rapport au niveau",
    ["Display Values"] = "Valeurs affichées",
--	["Mobs to kill till level (at %d XP)"] = true,
} end)
