local L = AceLibrary("AceLocale-2.2"):new("ExperienceFu")

L:RegisterTranslations("zhCN", function() return {
    ["Current XP"] = "当前经验",
    ["Display Value as..."] = "显示数值为...",
    ["Display Values"] = "显示数值",
    ["Display various XP statistics"] = "显示多种经验统计",
    ["Gained"] = "获取",
    ["Hide Text at maximum level"] = "达到最高级别隐藏文字",
    ["Level"] = "级别",
    ["Pet XP"] = "宠物经验",
--    ["Pet level"] = true,
    ["Remaining"] = "剩余",
    ["Reset session"] = "重置本次连接统计",
    ["Rest XP"] = "奖励经验",
    ["Show XP/hour"] = "显示 XP/小时",
    ["Show current XP percent"] = "显示当前经验百分比",
    ["Show current XP until level"] = "显示当前升级需要经验",
    ["Show current XP value"] = "显示当前经验值",
    ["Show current XP"] = "显示当前经验",
    ["Show in relation to level"] = "显示当前等级相对的经验",
    ["Show percent"] = "显示百分比",
    ["Show pet XP percent"] = "显示宠物经验百分比",
    ["Show pet XP until level"] = "显示宠物升级需要经验",
    ["Show pet XP value"] = "显示宠物经验值",
    ["Show pet XP"] = "显示宠物经验",
    ["Show rest XP percent"] = "显示奖励经验百分比",
    ["Show rest XP value"] = "显示奖励经验值",
    ["Show rest XP"] = "显示奖励经验",
    ["Show time to level"] = "显示升级预估时间",
    ["Show value"] = "显示值",
    ["Statistics"] = "统计",
    ["Time this level"] = "当前等级游戏时间",
    ["Time this session"] = "本次连接游戏时间",
    ["Time to level for this level"] = "升级时间(按等级效率)",
    ["Time to level for this session"] = "升级时间(按连接效率)",
    ["Toggle between showing experience as an absolute or in relation to time."] = "切换显示绝对值或者针对时间的相对值",
    ["Total XP this level"] = "当前等级所需经验",
    ["Total XP this session"] = "本次连接总经验",
    ["Total time played"] = "总游戏时间",
    ["View as Remaining XP"] = "显示为剩余经验",
    ["XP/hour this level"] = "当前级别 XP/小时",
    ["XP/hour this session"] = "本次连接 XP/小时",
--	["Mobs to kill till level (at %d XP)"] = true,
} end)

