local L = AceLibrary("AceLocale-2.2"):new("ExperienceFu")

L:RegisterTranslations("koKR", function() return {
    ["Current XP"] = "현재 경험치 보기",
    ["Display Value as..."] = "수치 표시중...",
    ["Display Values"] = "수치 표시",
    ["Display various XP statistics"] = "각종 경험치 통계 표시",
    ["Gained"] = "얻은 경험치",
    ["Hide Text at maximum level"] = "만랩에서 텍스트 숨김",
    ["Level"] = "레벨",
    ["Pet level"] = "소환수 레벨",
    ["Pet XP"] = "소환수 경험치",
    ["Remaining"] = "남은 경험치",
    ["Reset session"] = "세션 초기화",
    ["Rest XP"] = "휴식 경험치 보기",
    ["Show XP/hour"] = "시간당 경험치 보기",
    ["Show current XP percent"] = "현재 경험치 퍼센트 보기",
    ["Show current XP until level"] = "현재 레벨업까지 남은량 보기",
    ["Show current XP value"] = "현재 경험치 수치 보기",
    ["Show current XP"] = "현재 경험치 보기",
    ["Show in relation to level"] = "레벨 기준으로 보기",
    ["Show percent"] = "퍼센트 보기",
    ["Show pet XP percent"] = "소환수 경험치 퍼센트 보기",
    ["Show pet XP until level"] = "소환수 레벨업까지 남은량 보기",
    ["Show pet XP value"] = "소환수 경험치 수치 보기",
    ["Show pet XP"] = "소환수 경험치 보기",
    ["Show rest XP percent"] = "휴식 경험치 퍼센트 보기",
    ["Show rest XP value"] = "휴식 경험치 수치 보기",
    ["Show rest XP"] = "휴식 경험치 보기",
    ["Show time to level"] = "레벨업까지의 시간 보기",
    ["Show value"] = "수치 보기",
    ["Statistics"] = "통계",
    ["Time this level"] = "현재 레벨의 플레이 시간",
    ["Time this session"] = "현재 세션의 플레이 시간",
    ["Time to level for this level"] = "현재 레벨에서 레벨업까지의 시간",
    ["Time to level for this session"] = "현재 세션에서 레벨업까지의 시간",
    ["Toggle between showing experience as an absolute or in relation to time."] = "경험치 보기나 휴식 시간 보기로 전환합니다.",
    ["Total XP this level"] = "현재 레벨의 총 경험치",
    ["Total XP this session"] = "현재 세션동안 얻은 경험치",
    ["Total time played"] = "총 플레이 시간",
    ["View as Remaining XP"] = "남은 경험치 보기",
    ["XP/hour this level"] = "현재 레벨에서 시간당 경험치",
    ["XP/hour this session"] = "현재 세션에서 시간당 경험치",
	["Mobs to kill till level (at %d XP)"] = "레벨업까지 필요한 몬스터를 잡아야하는 개체 수(%d 경험치에서)",
} end)

